//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetDBWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetSubTypeProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetSubTypeProperty()
        {
            this.AssetSubTypePropertyValues = new HashSet<AssetSubTypePropertyValue>();
        }
    
        public int AssetSubTypePropertyID { get; set; }
        public int AssetSubType { get; set; }
        public string AssetSubTypeProperty1 { get; set; }
    
        public virtual AssetSubType AssetSubType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetSubTypePropertyValue> AssetSubTypePropertyValues { get; set; }
    }
}
