//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetDBWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetRelationship
    {
        public int AssetID { get; set; }
        public int RelatedAssetID { get; set; }
        public string Relationship { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Asset Asset1 { get; set; }
    }
}
